# Base Information
group_name: "OpenStudioLandscapes_Ayon"
key_prefixes:
  - "OpenStudioLandscapes_Ayon"

#compose_scope: "default"

#enabled: true

#docker_compose_override: "{DOT_LANDSCAPES}/{LANDSCAPE}/{FEATURE}/docker_compose/docker-compose.override.yml"

#ayon_port_container: 5000
#ayon_port_host: 5005

# Inside Landscape (ephemeral):
#ayon_db_install_destination: "{DOT_LANDSCAPES}/{LANDSCAPE}/{FEATURE}/data/ayon-db"
# In Landscapes root:
# Todo:
#  - [ ] does {DOT_SHARED_VOLUMES}/{GROUP}__{KEY} actually resolve? I don't think so...
#ayon_db_install_destination: "{DOT_LANDSCAPES}/{DOT_SHARED_VOLUMES}/{GROUP}__{KEY}/data/ayon-db"

#repository_url: "https://github.com/ynput/ayon-docker.git"
#branch: "main"
#docker_compose_yml: "docker-compose.yml"
#docker_compose_worker_yml: "docker-compose.worker.yml"